# baseurl = "https://WinterTechForum.github.io"
baseurl = "http://WinterTechForum.com"
languageCode = "en-us"
title = "Winter Tech Forum: A Self-Organizing Open Spaces Conference in Crested Butte, Colorado Feb 26 - March 2, 2018"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "A Self-Organizing Open Spaces Conference."

	logo = "/images/wtf-web.jpg"
	favicon = "images/wtf-favicon-96.ico"
	banner_image = "/images/WinterTechForumBanner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "WinterTechForum"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
	name   = "Overview"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Conference Theme"
	url    = "conference-theme/"
	weight = 20

[[menu.main]]
	name   = "Open Spaces"
	url    = "open-spaces/"
	weight = 30

[[menu.main]]
	name   = "Schedule"
	url    = "schedule/"
	weight = 40

[[menu.main]]
	name   = "Lightning Talks"
	url    = "lightning/"
	weight = 42

[[menu.main]]
	name   = "Hackathon"
	url    = "hackathon/"
	weight = 43

[[menu.main]]
	name   = "Afternoon Activities"
	url    = "afternoon/"
	weight = 47

[[menu.main]]
	name   = "Code of Conduct"
	url    = "https://github.com/WinterTechForum/wtf-code-of-conduct/blob/master/README.md"
	weight = 48

[[menu.main]]
	name   = "Location"
	url    = "location/"
	weight = 50

[[menu.main]]
	name   = "Venue"
	url    = "venue/"
	weight = 55

[[menu.main]]
	name   = "Travel"
	url    = "travel/"
	weight = 60

[[menu.main]]
	name   = "Lodging"
	url    = "lodging/"
	weight = 70

[[menu.main]]
	name   = "Altitude"
	url    = "altitude/"
	weight = 80

[[menu.main]]
	name   = "Registration"
	url    = "registration/"
	weight = 90

[[menu.main]]
	name   = "Contact"
	url    = "contact/"
	weight = 100


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
